# Generated by Django 2.2.4 on 2019-11-19 02:57

from django.db import migrations, models
import test_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('drink', 'Drink'), ('main_dish', 'Main Dish')], max_length=25)),
                ('ingredients', models.TextField(validators=[test_app.models.validate_ingredients])),
            ],
        ),
    ]
